import Navbar from "@/components/Navbar";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Notes Management App",
  description: "Generated by David",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased overflow-hidden">
        {/* Navbar */}
        <Navbar />

        {/* Sidebar + Content */}
        <div className="flex  h-screen">
          {/* Sidebar */}
          <Sidebar />

          {/* Main Content (Scrollable) */}
          <main className="flex-1 overflow-y-auto p-6 bg-gray-50">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
